spring:
  application:
    name: stock-dividend

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:snowball;DB_CLOSE_DELAY=-1
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: N3EdUMIXlU8C6Kb5MxSMeCUz4U5oN90ZdPwJGzoVAGUXNKQTmg5fA1f1r9ioYvUxH883oX1dlUNlJJoZ_DdUYw


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
